# Plugin Messages
messages:
  permission_denied: You do not have permission to manage BlockShuffle.
  usage: "Usage: %s"
  started: "Started BlockShuffle"
  stopped: "Stopped BlockShuffle"
  title: "BlockShuffle Round #%d - %s"
  starting: "BlockShuffle is starting! There are %d players."
  failed: "%s failed to find their block!"
  block_chosen: "You must stand on %s."
  block_found: "%s has found %s!"

# Number of rounds until difficulty increases (Early/Mid/Late)
difficulty_interval: 5

# First round length (ticks, 12000 = 10 minutes)
first_round_time: 12000

# Subsequent round length (ticks, 6000 = 5 minutes)
round_time: 6000

# Block configuration.
# See list here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
early_game_blocks:
  - ACTIVATOR_RAIL
  - ALLIUM
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
  - AZURE_BLUET
  - BAMBOO
  - BARREL
  - BEDROCK
  - BEETROOTS
  - BELL
  - BIRCH_BUTTON
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SAPLING
  - BIRCH_SIGN
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BIRCH_WOOD
  - BLACK_BANNER
  - BLACK_BED
  - BLACK_CARPET
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_STAINED_GLASS_PANE
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLAST_FURNACE
  - BLUE_BANNER
  - BLUE_BED
  - BLUE_CARPET
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_ORCHID
  - BLUE_STAINED_GLASS
  - BLUE_STAINED_GLASS_PANE
  - BLUE_TERRACOTTA
  - BLUE_WOOL
  - BONE_BLOCK
  - BOOKSHELF
  - BRICKS
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - BROWN_BANNER
  - BROWN_BED
  - BROWN_CARPET
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM
  - BROWN_STAINED_GLASS
  - BROWN_STAINED_GLASS_PANE
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - BUBBLE_COLUMN
  - CACTUS
  - CAMPFIRE
  - CARROTS
  - CARTOGRAPHY_TABLE
  - CARVED_PUMPKIN
  - CAULDRON
  - CHAIN
  - CHEST
  - CLAY
  - COAL_BLOCK
  - COAL_ORE
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COCOA
  - COMPOSTER
  - CORNFLOWER
  - CRAFTING_TABLE
  - CYAN_BANNER
  - CYAN_BED
  - CYAN_CARPET
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_STAINED_GLASS_PANE
  - CYAN_TERRACOTTA
  - CYAN_WOOL
  - DANDELION
  - DIAMOND_ORE
  - DIORITE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DISPENSER
  - DRIED_KELP_BLOCK
  - DROPPER
  - FARMLAND
  - FERN
  - FIRE
  - FLETCHING_TABLE
  - FLOWER_POT
  - FURNACE
  - GLASS
  - GLASS_PANE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS
  - GRASS_BLOCK
  - GRASS_PATH
  - GRAVEL
  - GRAY_BANNER
  - GRAY_BED
  - GRAY_CARPET
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_STAINED_GLASS
  - GRAY_STAINED_GLASS_PANE
  - GRAY_TERRACOTTA
  - GRAY_WOOL
  - GREEN_BANNER
  - GREEN_BED
  - GREEN_CARPET
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_STAINED_GLASS
  - GREEN_STAINED_GLASS_PANE
  - GREEN_TERRACOTTA
  - GREEN_WOOL
  - GRINDSTONE
  - HAY_BLOCK
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - HOPPER
  - ICE
  - IRON_BARS
  - IRON_BLOCK
  - IRON_DOOR
  - IRON_ORE
  - IRON_TRAPDOOR
  - JACK_O_LANTERN
  - JUKEBOX
  - KELP
  - KELP_PLANT
  - LADDER
  - LANTERN
  - LARGE_FERN
  - LAVA
  - LECTERN
  - LEVER
  - LIGHT_BLUE_BANNER
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CARPET
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BANNER
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CARPET
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_GRAY_WOOL
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LILAC
  - LILY_OF_THE_VALLEY
  - LILY_PAD
  - LIME_BANNER
  - LIME_BED
  - LIME_CARPET
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_STAINED_GLASS_PANE
  - LIME_TERRACOTTA
  - LIME_WOOL
  - LOOM
  - MAGENTA_BANNER
  - MAGENTA_BED
  - MAGENTA_CARPET
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_STAINED_GLASS
  - MAGENTA_STAINED_GLASS_PANE
  - MAGENTA_TERRACOTTA
  - MAGENTA_WOOL
  - MAGMA_BLOCK
  - MELON
  - MELON_STEM
  - MOSSY_COBBLESTONE
  - MUSHROOM_STEM
  - NETHERRACK
  - NOTE_BLOCK
  - OAK_BUTTON
  - OAK_DOOR
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SAPLING
  - OAK_SIGN
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - OBSIDIAN
  - ORANGE_BANNER
  - ORANGE_BED
  - ORANGE_CARPET
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_STAINED_GLASS_PANE
  - ORANGE_TERRACOTTA
  - ORANGE_TULIP
  - ORANGE_WOOL
  - OXEYE_DAISY
  - PACKED_ICE
  - PEONY
  - PINK_BANNER
  - PINK_BED
  - PINK_CARPET
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_STAINED_GLASS_PANE
  - PINK_TERRACOTTA
  - PINK_TULIP
  - PINK_WOOL
  - PISTON
  - POLISHED_ANDESITE
  - POLISHED_ANDESITE_SLAB
  - POLISHED_ANDESITE_STAIRS
  - POLISHED_DIORITE
  - POLISHED_DIORITE_SLAB
  - POLISHED_DIORITE_STAIRS
  - POLISHED_GRANITE
  - POLISHED_GRANITE_SLAB
  - POLISHED_GRANITE_STAIRS
  - POPPY
  - POTATOES
  - POTTED_ALLIUM
  - POTTED_AZURE_BLUET
  - POTTED_BIRCH_SAPLING
  - POTTED_BLUE_ORCHID
  - POTTED_BROWN_MUSHROOM
  - POTTED_CACTUS
  - POTTED_CORNFLOWER
  - POTTED_DANDELION
  - POTTED_DEAD_BUSH
  - POTTED_FERN
  - POTTED_LILY_OF_THE_VALLEY
  - POTTED_OAK_SAPLING
  - POTTED_ORANGE_TULIP
  - POTTED_OXEYE_DAISY
  - POTTED_PINK_TULIP
  - POTTED_POPPY
  - POTTED_RED_MUSHROOM
  - POTTED_RED_TULIP
  - POTTED_SPRUCE_SAPLING
  - POTTED_WHITE_TULIP
  - PUMPKIN
  - PUMPKIN_STEM
  - PURPLE_BANNER
  - PURPLE_BED
  - PURPLE_CARPET
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_STAINED_GLASS_PANE
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - RAIL
  - REDSTONE_ORE
  - REDSTONE_TORCH
  - REDSTONE_WIRE
  - RED_BANNER
  - RED_BED
  - RED_CARPET
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_GLAZED_TERRACOTTA
  - RED_MUSHROOM
  - RED_STAINED_GLASS
  - RED_STAINED_GLASS_PANE
  - RED_TERRACOTTA
  - RED_TULIP
  - RED_WOOL
  - REPEATER
  - ROSE_BUSH
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SCAFFOLDING
  - SEAGRASS
  - SLIME_BLOCK
  - SMITHING_TABLE
  - SMOKER
  - SMOOTH_SANDSTONE
  - SMOOTH_SANDSTONE_SLAB
  - SMOOTH_SANDSTONE_STAIRS
  - SMOOTH_STONE
  - SMOOTH_STONE_SLAB
  - SNOW
  - SNOW_BLOCK
  - SPRUCE_BUTTON
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SAPLING
  - SPRUCE_SIGN
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WOOD
  - STONE
  - STONECUTTER
  - STONE_BRICKS
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICK_WALL
  - STONE_BUTTON
  - STONE_PRESSURE_PLATE
  - STONE_SLAB
  - STONE_STAIRS
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TALL_GRASS
  - TALL_SEAGRASS
  - TARGET
  - TERRACOTTA
  - TNT
  - TORCH
  - TRAPPED_CHEST
  - TRIPWIRE
  - TRIPWIRE_HOOK
  - TWISTING_VINES
  - VINE
  - WATER
  - WEEPING_VINES
  - WHEAT
  - WHITE_BANNER
  - WHITE_BED
  - WHITE_CARPET
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - WHITE_TERRACOTTA
  - WHITE_TULIP
  - WHITE_WOOL
  - YELLOW_BANNER
  - YELLOW_BED
  - YELLOW_CARPET
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_STAINED_GLASS_PANE
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
mid_game_blocks:
  - ACACIA_BUTTON
  - ACACIA_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SAPLING
  - ACACIA_SIGN
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - ANCIENT_DEBRIS
  - BAMBOO_SAPLING
  - BASALT
  - BEEHIVE
  - BEE_NEST
  - BLACKSTONE
  - BLACKSTONE_SLAB
  - BLACKSTONE_STAIRS
  - BLACKSTONE_WALL
  - BRAIN_CORAL
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BRAIN_CORAL_WALL_FAN
  - BREWING_STAND
  - BROWN_MUSHROOM_BLOCK
  - BUBBLE_CORAL
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - BUBBLE_CORAL_WALL_FAN
  - CAKE
  - CHISELED_NETHER_BRICKS
  - CHISELED_POLISHED_BLACKSTONE
  - CHISELED_QUARTZ_BLOCK
  - CHISELED_RED_SANDSTONE
  - CHISELED_SANDSTONE
  - CHISELED_STONE_BRICKS
  - COARSE_DIRT
  - COMPARATOR
  - CONDUIT
  - CRACKED_NETHER_BRICKS
  - CRACKED_POLISHED_BLACKSTONE_BRICKS
  - CRACKED_STONE_BRICKS
  - CRIMSON_BUTTON
  - CRIMSON_DOOR
  - CRIMSON_FENCE
  - CRIMSON_FENCE_GATE
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_PLANKS
  - CRIMSON_PRESSURE_PLATE
  - CRIMSON_ROOTS
  - CRIMSON_SIGN
  - CRIMSON_SLAB
  - CRIMSON_STAIRS
  - CRIMSON_STEM
  - CRIMSON_TRAPDOOR
  - CRYING_OBSIDIAN
  - CUT_RED_SANDSTONE
  - CUT_RED_SANDSTONE_SLAB
  - CUT_SANDSTONE
  - CUT_SANDSTONE_SLAB
  - DARK_OAK_BUTTON
  - DARK_OAK_DOOR
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_PRESSURE_PLATE
  - DARK_OAK_SAPLING
  - DARK_OAK_SIGN
  - DARK_OAK_SLAB
  - DARK_OAK_STAIRS
  - DARK_OAK_TRAPDOOR
  - DARK_OAK_WOOD
  - DARK_PRISMARINE
  - DARK_PRISMARINE_SLAB
  - DARK_PRISMARINE_STAIRS
  - DAYLIGHT_DETECTOR
  - DEAD_BUSH
  - DETECTOR_RAIL
  - EMERALD_ORE
  - ENCHANTING_TABLE
  - FIRE_CORAL
  - FIRE_CORAL_BLOCK
  - FIRE_CORAL_FAN
  - FIRE_CORAL_WALL_FAN
  - GILDED_BLACKSTONE
  - GLOWSTONE
  - GOLD_BLOCK
  - GOLD_ORE
  - HONEYCOMB_BLOCK
  - HONEY_BLOCK
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - HORN_CORAL_WALL_FAN
  - JUNGLE_BUTTON
  - JUNGLE_DOOR
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SAPLING
  - JUNGLE_SIGN
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_TRAPDOOR
  - JUNGLE_WOOD
  - LAPIS_BLOCK
  - LAPIS_ORE
  - MOSSY_COBBLESTONE_SLAB
  - MOSSY_COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE_WALL
  - MOSSY_STONE_BRICKS
  - MOSSY_STONE_BRICK_SLAB
  - MOSSY_STONE_BRICK_STAIRS
  - MOSSY_STONE_BRICK_WALL
  - MYCELIUM
  - NETHER_BRICKS
  - NETHER_BRICK_FENCE
  - NETHER_BRICK_SLAB
  - NETHER_BRICK_STAIRS
  - NETHER_BRICK_WALL
  - NETHER_GOLD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_SPROUTS
  - NETHER_WART
  - NETHER_WART_BLOCK
  - OBSERVER
  - PETRIFIED_OAK_SLAB
  - PODZOL
  - POLISHED_BASALT
  - POLISHED_BLACKSTONE
  - POLISHED_BLACKSTONE_BRICKS
  - POLISHED_BLACKSTONE_BRICK_SLAB
  - POLISHED_BLACKSTONE_BRICK_STAIRS
  - POLISHED_BLACKSTONE_BRICK_WALL
  - POLISHED_BLACKSTONE_BUTTON
  - POLISHED_BLACKSTONE_PRESSURE_PLATE
  - POLISHED_BLACKSTONE_SLAB
  - POLISHED_BLACKSTONE_STAIRS
  - POLISHED_BLACKSTONE_WALL
  - POTTED_ACACIA_SAPLING
  - POTTED_BAMBOO
  - POTTED_CRIMSON_FUNGUS
  - POTTED_CRIMSON_ROOTS
  - POTTED_DARK_OAK_SAPLING
  - POTTED_JUNGLE_SAPLING
  - POTTED_WARPED_FUNGUS
  - POTTED_WARPED_ROOTS
  - POWERED_RAIL
  - PRISMARINE
  - PRISMARINE_BRICKS
  - PRISMARINE_BRICK_SLAB
  - PRISMARINE_BRICK_STAIRS
  - PRISMARINE_SLAB
  - PRISMARINE_STAIRS
  - PRISMARINE_WALL
  - QUARTZ_BLOCK
  - QUARTZ_BRICKS
  - QUARTZ_PILLAR
  - QUARTZ_SLAB
  - QUARTZ_STAIRS
  - REDSTONE_BLOCK
  - REDSTONE_LAMP
  - RED_MUSHROOM_BLOCK
  - RED_NETHER_BRICKS
  - RED_NETHER_BRICK_SLAB
  - RED_NETHER_BRICK_STAIRS
  - RED_NETHER_BRICK_WALL
  - RED_SAND
  - RED_SANDSTONE
  - RED_SANDSTONE_SLAB
  - RED_SANDSTONE_STAIRS
  - RED_SANDSTONE_WALL
  - SEA_LANTERN
  - SEA_PICKLE
  - SHROOMLIGHT
  - SMOOTH_QUARTZ
  - SMOOTH_QUARTZ_SLAB
  - SMOOTH_QUARTZ_STAIRS
  - SMOOTH_RED_SANDSTONE
  - SMOOTH_RED_SANDSTONE_SLAB
  - SMOOTH_RED_SANDSTONE_STAIRS
  - SOUL_CAMPFIRE
  - SOUL_FIRE
  - SOUL_LANTERN
  - SOUL_SAND
  - SOUL_SOIL
  - SOUL_TORCH
  - SPAWNER
  - SPONGE
  - STICKY_PISTON
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_CRIMSON_HYPHAE
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_WARPED_HYPHAE
  - STRIPPED_WARPED_STEM
  - TUBE_CORAL
  - TUBE_CORAL_BLOCK
  - TUBE_CORAL_FAN
  - TUBE_CORAL_WALL_FAN
  - TURTLE_EGG
  - TWISTING_VINES_PLANT
  - WARPED_BUTTON
  - WARPED_DOOR
  - WARPED_FENCE
  - WARPED_FENCE_GATE
  - WARPED_FUNGUS
  - WARPED_HYPHAE
  - WARPED_NYLIUM
  - WARPED_PLANKS
  - WARPED_PRESSURE_PLATE
  - WARPED_ROOTS
  - WARPED_SIGN
  - WARPED_SLAB
  - WARPED_STAIRS
  - WARPED_STEM
  - WARPED_TRAPDOOR
  - WARPED_WART_BLOCK
  - WEEPING_VINES_PLANT
  - WET_SPONGE
late_game_blocks:
  - BEACON
  - BLACK_SHULKER_BOX
  - BLUE_ICE
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CHORUS_FLOWER
  - CHORUS_PLANT
  - CYAN_SHULKER_BOX
  - DEAD_BRAIN_CORAL
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BRAIN_CORAL_WALL_FAN
  - DEAD_BUBBLE_CORAL
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_BUBBLE_CORAL_WALL_FAN
  - DEAD_FIRE_CORAL
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_FAN
  - DEAD_FIRE_CORAL_WALL_FAN
  - DEAD_HORN_CORAL
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_HORN_CORAL_FAN
  - DEAD_HORN_CORAL_WALL_FAN
  - DEAD_TUBE_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_TUBE_CORAL_FAN
  - DEAD_TUBE_CORAL_WALL_FAN
  - DIAMOND_BLOCK
  - DRAGON_EGG
  - EMERALD_BLOCK
  - ENDER_CHEST
  - END_PORTAL_FRAME
  - END_ROD
  - END_STONE
  - END_STONE_BRICKS
  - END_STONE_BRICK_SLAB
  - END_STONE_BRICK_STAIRS
  - END_STONE_BRICK_WALL
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - LODESTONE
  - MAGENTA_SHULKER_BOX
  - NETHERITE_BLOCK
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - PURPUR_BLOCK
  - PURPUR_PILLAR
  - PURPUR_SLAB
  - PURPUR_STAIRS
  - RED_SHULKER_BOX
  - RESPAWN_ANCHOR
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - WITHER_SKELETON_SKULL
  - YELLOW_SHULKER_BOX
